version: '3.3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    networks:
      - my_network
    volumes:
      - ..:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - postgreDB
      - mongoDB
      - cacheRedis
    environment:
      - DATABASE_URL=postgresql://stud:stud@postgreDB/archdb

  postgreDB:
    image: postgres:14
    container_name: postgreDB
    networks:
      - my_network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=stud
      - POSTGRES_PASSWORD=stud
      - POSTGRES_DB=archdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongoDB:
    image: mongo:5.0
    container_name: mongoDB
    restart: on-failure
    networks:
      - my_network
    volumes:
      - mongoDBdata:/data/mongoDB
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - "27017:27017"
    healthcheck:
      test: echo "db.runCommand('ping').ok" | mongosh localhost:27017/test --quiet

  cacheRedis:
    image: redis:6.2-alpine
    container_name: cacheRedis
    restart: always
    networks:
      - my_network
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning

networks:
  my_network:
volumes:
  postgres-data:
  mongoDBdata: